Avoid triggering error with -Werror=unused-value
Fedora RPMs are compiled using -Wall which includes
-Werror=unused-value.  On architecures that do not have Dyninst
support the flush_analysis_caches define in analysis.h would trigger
the following error:

In file included from elaborate.cxx:20:
elaborate.cxx: In function ‘void build_no_more(systemtap_session&)’:
analysis.h:30:34: error: statement has no effect [-Werror=unused-value]
   30 | #define flush_analysis_caches() (0)
      |                                 ~^~
elaborate.cxx:1871:3: note: in expansion of macro ‘flush_analysis_caches’
 1871 |   flush_analysis_caches();
      |   ^~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Tweaked the flush_analysis_caches define to avoid creating an unused
value.